### ISSUE TITLE
not exporting with custom startup file

### ISSUE THREAD

**Issue by Chax-ai** [Tilapiatsu/blender-export_as_blend#1]
hey i have changed my startup file to a different settings but when the addon exports the blend file its using blenders default startup file can u guide me where is the code to change the file to use while exporting

**Comment by Tilapiatsu** [comment]
Hello @Chaxmax2004.
If you want to export with your startup file, you can just untick "Export to clean File". Let me know if it helps :)

**Comment by Chax-ai** [comment]
> 

hey i know that if i want to export to startup file I have to untick "Export to clean file" but the thing is I have a custom startup file instead of blenders default startup file I have replaced the blenders default startup file with my custom startup file still the addon is exporting the files with blenders default startup file can u give me the path that the addon takes the startup file?? so I can replace it with my custom startup file thanks

**Comment by Tilapiatsu** [comment]
Sorry I think I haven't explained correctly:
- If you Tick "Export to clean file" you will export with the factory default scene ( which is embeded into blender )
- if you UNTick "export to clean file" you will export with whatever custom startup file you have setup

Let me know if it is clearer to you ?

**Comment by Chax-ai** [comment]
> 

brother the main problem is that its not exporting to my custom startup file even the I untick "export to clean file" I changed my custom file in my config folder
![image](https://github.com/Tilapiatsu/blender-export_as_blend/assets/100697692/642b9774-946f-44d2-902e-40df4e6e444e)

**Comment by lynrayy** [comment]
SAME

**Comment by lynrayy** [comment]
Just not saving export

**Comment by Tilapiatsu** [comment]
Hi @Chax-ai  @lynrayy
I'm sorry for the long delay,
I've made a quick fix for the issue you mentionned. It should be fixed with 2.0.1.
Please give a try and let me know if it is better for you.
Cheers

**Comment by Tilapiatsu** [comment]
@Chax-ai @lynrayy 
Did you had the chance to try with the new version ?

**Comment by Chax-ai** [comment]
Yes it's working i have used it

**Comment by Tilapiatsu** [comment]
Thanks for th confirmation :)
Closing the issue
